"""Add specs to monitor

Revision ID: fbac658c9a3
Revises: c022bd6f985
Create Date: 2013-09-02 16:55:40.725558

"""

# revision identifiers, used by Alembic.
revision = 'fbac658c9a3'
down_revision = 'c022bd6f985'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitor', sa.Column('specs', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitor', 'specs')
    ### end Alembic commands ###
